[project]
name = "congestion-pricing-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.4.3",
    "numpy>=2.3.0",
    "pandas>=2.3.0",
    "praw>=7.8.1",
]
